# -*- coding: utf-8 -*-
"""generar_datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLayTdgBCN_zdCJMBNL75lRFMDTnhPh0
"""

!pip install faker

#@title Datos
# generar_datos.py
# Generación reproducible de datos sintéticos para AndinaRetail S.A.C.
# Python 3.11

from pathlib import Path
import random
from typing import Dict, List

import numpy as np
import pandas as pd
from faker import Faker


# ============================================================
# CONFIGURACIÓN GENERAL
# ============================================================

SEED = 2026

np.random.seed(SEED)
random.seed(SEED)
Faker.seed(SEED)

fake = Faker("es_ES")

OUTPUT_DIR = Path("datos")

N_TIENDAS = 12
N_PRODUCTOS = 800
N_CLIENTES = 15_000
N_VENTAS = 250_000

FECHA_INICIO_VENTAS = pd.Timestamp("2023-01-01")
FECHA_FIN_VENTAS = pd.Timestamp("2025-12-31")
FECHA_CORTE_CHURN = pd.Timestamp("2025-12-31")

CIUDADES = ["Lima", "Arequipa", "Trujillo", "Cusco", "Piura"]

REGIONES = {
    "Lima": "Costa Centro",
    "Arequipa": "Sur",
    "Trujillo": "Norte",
    "Cusco": "Sur Andino",
    "Piura": "Norte",
}

DISTRITOS = {
    "Lima": [
        "Miraflores", "San Isidro", "Surco", "Los Olivos",
        "San Miguel", "La Molina", "Comas", "Ate"
    ],
    "Arequipa": [
        "Cercado", "Yanahuara", "Cayma", "José Luis Bustamante",
        "Paucarpata", "Socabaya"
    ],
    "Trujillo": [
        "Trujillo", "Víctor Larco", "El Porvenir",
        "La Esperanza", "Huanchaco", "Moche"
    ],
    "Cusco": [
        "Cusco", "Wanchaq", "San Sebastián",
        "Santiago", "San Jerónimo"
    ],
    "Piura": [
        "Piura", "Castilla", "Veintiséis de Octubre",
        "Catacaos", "Tambogrande"
    ],
}

CATEGORIAS = [
    "Abarrotes",
    "Bebidas",
    "Limpieza",
    "Cuidado Personal",
    "Electrohogar",
    "Hogar",
]

SUBCATEGORIAS = {
    "Abarrotes": ["Arroz", "Aceite", "Fideos", "Conservas", "Menestras", "Harinas"],
    "Bebidas": ["Gaseosas", "Jugos", "Agua", "Energizantes", "Infusiones"],
    "Limpieza": ["Detergente", "Lavavajilla", "Desinfectante", "Suavizante", "Lejía"],
    "Cuidado Personal": ["Shampoo", "Jabón", "Crema Dental", "Desodorante", "Papel Higiénico"],
    "Electrohogar": ["Licuadora", "Microondas", "Refrigeradora", "Televisor", "Lavadora", "Plancha"],
    "Hogar": ["Sábanas", "Ollas", "Toallas", "Organizadores", "Vajilla", "Decoración"],
}

RANGOS_PRECIO = {
    "Abarrotes": (2.5, 45.0),
    "Bebidas": (2.0, 38.0),
    "Limpieza": (4.0, 75.0),
    "Cuidado Personal": (5.0, 120.0),
    "Electrohogar": (120.0, 3600.0),
    "Hogar": (15.0, 650.0),
}

MARCAS_FICTICIAS = [
    "Andesol", "Kawsay", "IntiMax", "Sumaq", "NortePlus",
    "Qori", "Altura", "Pacífico", "Wayra", "Rumi",
    "Pukara", "Misti", "CostaSur", "InkaHome", "SolRetail"
]

METODOS_PAGO_TIENDA = ["Efectivo", "Tarjeta Débito", "Tarjeta Crédito", "Yape", "Plin"]
METODOS_PAGO_DIGITAL = ["Tarjeta Débito", "Tarjeta Crédito", "Yape", "Plin", "Transferencia"]


# ============================================================
# UTILIDADES
# ============================================================

def crear_directorio_salida() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def fecha_aleatoria(inicio: str, fin: str, size: int) -> pd.Series:
    inicio_ts = pd.Timestamp(inicio)
    fin_ts = pd.Timestamp(fin)
    dias = (fin_ts - inicio_ts).days

    fechas = inicio_ts + pd.to_timedelta(
        np.random.randint(0, dias + 1, size=size),
        unit="D"
    )

    return pd.Series(fechas)


def insertar_faltantes(df: pd.DataFrame, columna: str, porcentaje: float) -> pd.DataFrame:
    df = df.copy()
    n = int(round(len(df) * porcentaje))

    indices = np.random.choice(df.index.to_numpy(), size=n, replace=False)
    df.loc[indices, columna] = np.nan

    return df


def margen_porcentual(df: pd.DataFrame) -> float:
    monto = df["monto_total"].sum()

    if monto == 0:
        return 0.0

    return df["margen_total"].sum() / monto


# ============================================================
# GENERACIÓN DE TIENDAS
# ============================================================

def generar_tiendas() -> pd.DataFrame:
    tiendas = [
        [1, "AndinaRetail Lima Centro", "Lima", REGIONES["Lima"], "Física", 950, "2018-03-15"],
        [2, "AndinaRetail Lima Norte", "Lima", REGIONES["Lima"], "Física", 870, "2019-06-10"],
        [3, "AndinaRetail Lima Sur", "Lima", REGIONES["Lima"], "Física", 820, "2020-01-20"],
        [4, "AndinaRetail Arequipa Mall", "Arequipa", REGIONES["Arequipa"], "Física", 760, "2019-08-12"],
        [5, "AndinaRetail Arequipa Cercado", "Arequipa", REGIONES["Arequipa"], "Física", 640, "2021-02-05"],
        [6, "AndinaRetail Trujillo Centro", "Trujillo", REGIONES["Trujillo"], "Física", 700, "2018-09-22"],
        [7, "AndinaRetail Trujillo Norte", "Trujillo", REGIONES["Trujillo"], "Física", 680, "2020-11-18"],
        [8, "AndinaRetail Cusco Centro", "Cusco", REGIONES["Cusco"], "Física", 620, "2021-04-14"],
        [9, "AndinaRetail Cusco Sur", "Cusco", REGIONES["Cusco"], "Física", 580, "2022-07-09"],
        [10, "AndinaRetail Piura Centro", "Piura", REGIONES["Piura"], "Física", 690, "2019-12-03"],
        [11, "AndinaRetail Piura Norte", "Piura", REGIONES["Piura"], "Física", 610, "2022-03-21"],
        [12, "AndinaRetail Digital Nacional", "Lima", "Nacional", "Virtual", 0, "2021-01-01"],
    ]

    return pd.DataFrame(
        tiendas,
        columns=[
            "id_tienda",
            "nombre",
            "ciudad",
            "region",
            "tipo",
            "area_m2",
            "fecha_apertura",
        ],
    )


# ============================================================
# GENERACIÓN DE PRODUCTOS
# ============================================================

def generar_productos() -> pd.DataFrame:
    registros = []

    pesos_categoria = np.array([0.22, 0.18, 0.17, 0.16, 0.12, 0.15])
    pesos_categoria = pesos_categoria / pesos_categoria.sum()

    categorias = np.random.choice(
        CATEGORIAS,
        size=N_PRODUCTOS,
        p=pesos_categoria
    )

    for i, categoria in enumerate(categorias, start=1):
        subcategoria = random.choice(SUBCATEGORIAS[categoria])
        marca = random.choice(MARCAS_FICTICIAS)

        precio_min, precio_max = RANGOS_PRECIO[categoria]

        if categoria == "Electrohogar":
            precio_lista = np.random.lognormal(
                mean=np.log((precio_min + precio_max) / 3),
                sigma=0.75
            )
            precio_lista = np.clip(precio_lista, precio_min, precio_max)
        else:
            precio_lista = np.random.uniform(precio_min, precio_max)

        precio_lista = round(float(precio_lista), 2)
        costo_unitario = round(precio_lista * np.random.uniform(0.60, 0.80), 2)

        fecha_alta = fecha_aleatoria("2021-01-01", "2025-12-31", 1).iloc[0].date()

        nombre_producto = f"{subcategoria} {marca} {fake.bothify(text='###')}"

        registros.append(
            {
                "id_producto": i,
                "nombre": nombre_producto,
                "categoria": categoria,
                "subcategoria": subcategoria,
                "marca": marca,
                "precio_lista": precio_lista,
                "costo_unitario": costo_unitario,
                "fecha_alta": fecha_alta,
            }
        )

    return pd.DataFrame(registros)


# ============================================================
# GENERACIÓN DE CLIENTES BASE
# ============================================================

def generar_clientes_base() -> pd.DataFrame:
    ciudades = np.random.choice(
        CIUDADES,
        size=N_CLIENTES,
        p=[0.45, 0.15, 0.16, 0.11, 0.13]
    )

    edades = np.random.normal(loc=38, scale=12, size=N_CLIENTES)
    edades = np.clip(np.round(edades), 18, 80).astype(int)

    generos = np.random.choice(
        ["Femenino", "Masculino", "Otro"],
        size=N_CLIENTES,
        p=[0.50, 0.48, 0.02]
    )

    canal_preferido = np.random.choice(
        ["Tienda", "Web", "App"],
        size=N_CLIENTES,
        p=[0.56, 0.27, 0.17]
    )

    actividad_tipo = np.random.choice(
        ["Alta", "Media", "Baja"],
        size=N_CLIENTES,
        p=[0.28, 0.47, 0.25]
    )

    actividad_score = np.select(
        [
            actividad_tipo == "Alta",
            actividad_tipo == "Media",
            actividad_tipo == "Baja",
        ],
        [
            np.random.uniform(1.60, 2.80, size=N_CLIENTES),
            np.random.uniform(0.75, 1.45, size=N_CLIENTES),
            np.random.uniform(0.15, 0.65, size=N_CLIENTES),
        ],
    )

    registros = []

    for i in range(N_CLIENTES):
        ciudad = ciudades[i]

        registros.append(
            {
                "id_cliente": i + 1,
                "nombre": fake.name(),
                "edad": int(edades[i]),
                "genero": generos[i],
                "ciudad": ciudad,
                "distrito": random.choice(DISTRITOS[ciudad]),
                "fecha_registro": fecha_aleatoria("2022-01-01", "2025-12-31", 1).iloc[0].date(),
                "canal_preferido": canal_preferido[i],
                "segmento": "Por clasificar",
                "actividad_tipo": actividad_tipo[i],
                "actividad_score": float(actividad_score[i]),
            }
        )

    return pd.DataFrame(registros)


# ============================================================
# GENERACIÓN DE FECHAS DE VENTA
# ============================================================

def generar_fechas_ventas(n: int) -> pd.Series:
    periodos = pd.period_range("2023-01", "2025-12", freq="M")

    pesos = []

    for periodo in periodos:
        peso = 1.0

        # Tendencia general creciente.
        peso *= 1.0 + ((periodo.year - 2023) * 0.12)

        # Estacionalidad fuerte.
        if periodo.month == 7:
            peso *= 1.55
        elif periodo.month == 12:
            peso *= 2.05
        elif periodo.month in [5, 11]:
            peso *= 1.15
        elif periodo.month in [1, 2]:
            peso *= 0.88

        pesos.append(peso)

    pesos = np.array(pesos)
    pesos = pesos / pesos.sum()

    indices_periodo = np.random.choice(
        np.arange(len(periodos)),
        size=n,
        p=pesos
    )

    periodos_elegidos = periodos[indices_periodo]

    anios = periodos_elegidos.year.to_numpy()
    meses = periodos_elegidos.month.to_numpy()

    dias = np.array([
        random.randint(1, periodo.days_in_month)
        for periodo in periodos_elegidos
    ])

    fechas = pd.to_datetime(
        {
            "year": anios,
            "month": meses,
            "day": dias,
        }
    )

    return pd.Series(fechas)


# ============================================================
# SELECCIÓN DE CANALES
# ============================================================

def generar_canales(fechas: pd.Series, clientes_venta: np.ndarray, clientes_df: pd.DataFrame) -> np.ndarray:
    clientes_lookup = clientes_df.set_index("id_cliente")

    preferencias = clientes_lookup.loc[clientes_venta, "canal_preferido"].to_numpy()
    anios = fechas.dt.year.to_numpy()

    progreso = (anios - 2023) / 2

    p_tienda = 0.70 - (0.21 * progreso)
    p_web = 0.20 + (0.10 * progreso)
    p_app = 0.10 + (0.11 * progreso)

    # Ajuste suave por preferencia del cliente.
    p_tienda = p_tienda + np.where(preferencias == "Tienda", 0.08, 0.00)
    p_web = p_web + np.where(preferencias == "Web", 0.06, 0.00)
    p_app = p_app + np.where(preferencias == "App", 0.06, 0.00)

    total = p_tienda + p_web + p_app
    p_tienda = p_tienda / total
    p_web = p_web / total
    p_app = p_app / total

    aleatorio = np.random.random(size=len(fechas))

    canales = np.where(
        aleatorio < p_tienda,
        "Tienda",
        np.where(
            aleatorio < p_tienda + p_web,
            "Web",
            "App"
        )
    )

    return canales


# ============================================================
# SELECCIÓN DE PRODUCTOS
# ============================================================

def elegir_categorias_venta(meses: np.ndarray, canales: np.ndarray) -> np.ndarray:
    categorias_resultado = np.empty(len(meses), dtype=object)

    base = {
        "Abarrotes": 0.23,
        "Bebidas": 0.18,
        "Limpieza": 0.17,
        "Cuidado Personal": 0.15,
        "Electrohogar": 0.12,
        "Hogar": 0.15,
    }

    for mes in np.unique(meses):
        for canal in ["Tienda", "Web", "App"]:
            mascara = (meses == mes) & (canales == canal)

            if mascara.sum() == 0:
                continue

            pesos = base.copy()

            if mes == 7:
                pesos["Abarrotes"] *= 1.25
                pesos["Bebidas"] *= 1.30
                pesos["Hogar"] *= 1.10

            if mes == 12:
                pesos["Electrohogar"] *= 1.65
                pesos["Hogar"] *= 1.45
                pesos["Cuidado Personal"] *= 1.15

            if canal in ["Web", "App"]:
                pesos["Electrohogar"] *= 1.35
                pesos["Hogar"] *= 1.20

            categorias = list(pesos.keys())
            valores = np.array(list(pesos.values()))
            probabilidades = valores / valores.sum()

            categorias_resultado[mascara] = np.random.choice(
                categorias,
                size=mascara.sum(),
                p=probabilidades
            )

    return categorias_resultado


# ============================================================
# GENERACIÓN DE VENTAS
# ============================================================

def generar_ventas(
    tiendas_df: pd.DataFrame,
    productos_df: pd.DataFrame,
    clientes_df: pd.DataFrame
) -> pd.DataFrame:

    fechas = generar_fechas_ventas(N_VENTAS)

    clientes_ids = clientes_df["id_cliente"].to_numpy()
    actividad = clientes_df["actividad_tipo"].to_numpy()
    pesos_base = clientes_df["actividad_score"].to_numpy()

    pesos_temprano = pesos_base / pesos_base.sum()

    pesos_tarde = pesos_base.copy()
    pesos_tarde[actividad == "Alta"] *= 1.25
    pesos_tarde[actividad == "Media"] *= 0.45
    pesos_tarde[actividad == "Baja"] *= 0.07
    pesos_tarde = pesos_tarde / pesos_tarde.sum()

    mascara_tarde = fechas >= pd.Timestamp("2025-10-02")

    clientes_venta = np.empty(N_VENTAS, dtype=int)

    clientes_venta[~mascara_tarde.to_numpy()] = np.random.choice(
        clientes_ids,
        size=(~mascara_tarde).sum(),
        p=pesos_temprano
    )

    clientes_venta[mascara_tarde.to_numpy()] = np.random.choice(
        clientes_ids,
        size=mascara_tarde.sum(),
        p=pesos_tarde
    )

    canales = generar_canales(fechas, clientes_venta, clientes_df)

    clientes_lookup = clientes_df.set_index("id_cliente")
    ciudades_cliente = clientes_lookup.loc[clientes_venta, "ciudad"].to_numpy()

    tiendas_fisicas = tiendas_df[tiendas_df["tipo"] == "Física"]
    tiendas_virtuales = tiendas_df[tiendas_df["tipo"] == "Virtual"]

    tiendas_por_ciudad = {
        ciudad: tiendas_fisicas[tiendas_fisicas["ciudad"] == ciudad]["id_tienda"].to_numpy()
        for ciudad in CIUDADES
    }

    id_tienda_virtual = tiendas_virtuales["id_tienda"].iloc[0]

    tiendas_venta = np.empty(N_VENTAS, dtype=int)

    mascara_digital = canales != "Tienda"
    tiendas_venta[mascara_digital] = id_tienda_virtual

    for ciudad in CIUDADES:
        mascara = (canales == "Tienda") & (ciudades_cliente == ciudad)
        tiendas_venta[mascara] = np.random.choice(
            tiendas_por_ciudad[ciudad],
            size=mascara.sum()
        )

    meses = fechas.dt.month.to_numpy()
    categorias_venta = elegir_categorias_venta(meses, canales)

    productos_por_categoria = {
        categoria: productos_df[productos_df["categoria"] == categoria]["id_producto"].to_numpy()
        for categoria in CATEGORIAS
    }

    productos_venta = np.empty(N_VENTAS, dtype=int)

    for categoria in CATEGORIAS:
        mascara = categorias_venta == categoria
        productos_venta[mascara] = np.random.choice(
            productos_por_categoria[categoria],
            size=mascara.sum()
        )

    productos_lookup = productos_df.set_index("id_producto")

    precio_lista = productos_lookup.loc[productos_venta, "precio_lista"].to_numpy()
    costo_unitario = productos_lookup.loc[productos_venta, "costo_unitario"].to_numpy()
    categoria_producto = productos_lookup.loc[productos_venta, "categoria"].to_numpy()

    precio_unitario = precio_lista * np.random.normal(loc=1.0, scale=0.025, size=N_VENTAS)
    precio_unitario = np.maximum(precio_unitario, costo_unitario * 1.05)
    precio_unitario = np.round(precio_unitario, 2)

    descuento = np.random.beta(a=2.2, b=14, size=N_VENTAS) * 0.35

    descuento += np.where(canales == "Web", 0.015, 0.00)
    descuento += np.where(canales == "App", 0.025, 0.00)
    descuento += np.where(categoria_producto == "Electrohogar", 0.025, 0.00)
    descuento += np.where(categoria_producto == "Hogar", 0.015, 0.00)
    descuento += np.where(meses == 12, 0.020, 0.00)
    descuento += np.where(meses == 7, 0.012, 0.00)

    tiendas_lookup = tiendas_df.set_index("id_tienda")
    ciudades_tienda = tiendas_lookup.loc[tiendas_venta, "ciudad"].to_numpy()

    mascara_trujillo_post_q2_2025 = (
        (ciudades_tienda == "Trujillo") &
        (fechas >= pd.Timestamp("2025-04-01")) &
        (canales == "Tienda")
    )

    descuento += np.where(
        mascara_trujillo_post_q2_2025.to_numpy(),
        np.random.uniform(0.08, 0.14, size=N_VENTAS),
        0.00
    )

    descuento = np.clip(descuento, 0.00, 0.35)
    descuento = np.round(descuento, 4)

    cantidad_base = np.random.choice(
        np.arange(1, 9),
        size=N_VENTAS,
        p=[0.43, 0.27, 0.12, 0.07, 0.04, 0.03, 0.025, 0.015]
    )

    factor_categoria = pd.Series(categoria_producto).map(
        {
            "Abarrotes": 1.15,
            "Bebidas": 1.12,
            "Limpieza": 1.00,
            "Cuidado Personal": 0.95,
            "Electrohogar": 0.55,
            "Hogar": 0.85,
        }
    ).to_numpy()

    factor_mes = np.ones(N_VENTAS)
    factor_mes[meses == 7] *= 1.18
    factor_mes[meses == 12] *= 1.35

    factor_canal = np.where(canales == "App", 1.08, np.where(canales == "Web", 1.05, 1.00))
    factor_descuento = 1 + (descuento * 1.45)

    ruido = np.random.normal(loc=0.0, scale=0.45, size=N_VENTAS)

    cantidad = np.round(
        cantidad_base * factor_categoria * factor_mes * factor_canal * factor_descuento + ruido
    ).astype(int)

    cantidad = np.clip(cantidad, 1, 8)

    # Outliers controlados de cantidad.
    n_outliers = int(N_VENTAS * 0.004)
    indices_outliers = np.random.choice(np.arange(N_VENTAS), size=n_outliers, replace=False)
    cantidad[indices_outliers] = np.random.randint(9, 19, size=n_outliers)

    monto_total = np.round(cantidad * precio_unitario * (1 - descuento), 2)
    margen_unitario = np.round(precio_unitario * (1 - descuento) - costo_unitario, 2)
    margen_total = np.round(monto_total - (cantidad * costo_unitario), 2)

    metodo_pago = np.empty(N_VENTAS, dtype=object)

    for canal in ["Tienda", "Web", "App"]:
        mascara = canales == canal

        if canal == "Tienda":
            metodo_pago[mascara] = np.random.choice(
                METODOS_PAGO_TIENDA,
                size=mascara.sum(),
                p=[0.28, 0.24, 0.26, 0.13, 0.09]
            )
        else:
            metodo_pago[mascara] = np.random.choice(
                METODOS_PAGO_DIGITAL,
                size=mascara.sum(),
                p=[0.26, 0.36, 0.18, 0.12, 0.08]
            )

    ventas_df = pd.DataFrame(
        {
            "id_venta": np.arange(1, N_VENTAS + 1),
            "fecha": fechas.dt.date,
            "id_cliente": clientes_venta,
            "id_tienda": tiendas_venta,
            "id_producto": productos_venta,
            "cantidad": cantidad,
            "precio_unitario": precio_unitario,
            "descuento_pct": descuento,
            "costo_unitario": np.round(costo_unitario, 2),
            "monto_total": monto_total,
            "margen_unitario": margen_unitario,
            "margen_total": margen_total,
            "canal": canales,
            "metodo_pago": metodo_pago,
        }
    )

    ventas_df["fecha"] = pd.to_datetime(ventas_df["fecha"])

    return ventas_df


# ============================================================
# ACTUALIZACIÓN DE CLIENTES CON CHURN
# ============================================================

def actualizar_clientes_con_churn(clientes_df: pd.DataFrame, ventas_df: pd.DataFrame) -> pd.DataFrame:
    clientes = clientes_df.copy()

    resumen = ventas_df.groupby("id_cliente").agg(
        fecha_primera_compra=("fecha", "min"),
        fecha_ultima_compra=("fecha", "max"),
        frecuencia_compras=("id_venta", "count"),
        valor_total=("monto_total", "sum")
    ).reset_index()

    clientes = clientes.merge(resumen, on="id_cliente", how="left")

    clientes["frecuencia_compras"] = clientes["frecuencia_compras"].fillna(0).astype(int)
    clientes["valor_total"] = clientes["valor_total"].fillna(0.0)

    clientes["fecha_ultima_compra"] = pd.to_datetime(clientes["fecha_ultima_compra"])
    clientes["fecha_primera_compra"] = pd.to_datetime(clientes["fecha_primera_compra"])
    clientes["fecha_registro"] = pd.to_datetime(clientes["fecha_registro"])

    clientes["dias_desde_ultima_compra"] = (
        FECHA_CORTE_CHURN - clientes["fecha_ultima_compra"]
    ).dt.days

    clientes.loc[
        clientes["fecha_ultima_compra"].isna(),
        "dias_desde_ultima_compra"
    ] = 999

    clientes["dias_desde_ultima_compra"] = clientes["dias_desde_ultima_compra"].astype(int)

    clientes["churn"] = np.where(
        clientes["dias_desde_ultima_compra"] > 90,
        1,
        0
    )

    # Ajustar fecha de registro para que no sea posterior a la primera compra.
    mascara_inconsistente = (
        clientes["fecha_primera_compra"].notna() &
        (clientes["fecha_registro"] > clientes["fecha_primera_compra"])
    )

    indices = clientes[mascara_inconsistente].index

    for idx in indices:
        primera_compra = clientes.loc[idx, "fecha_primera_compra"]
        inicio = pd.Timestamp("2022-01-01")
        fin = primera_compra

        if fin < inicio:
            nueva_fecha = inicio
        else:
            dias = (fin - inicio).days
            nueva_fecha = inicio + pd.to_timedelta(random.randint(0, dias), unit="D")

        clientes.loc[idx, "fecha_registro"] = nueva_fecha

    q25_freq = clientes["frecuencia_compras"].quantile(0.25)
    q75_freq = clientes["frecuencia_compras"].quantile(0.75)
    q75_valor = clientes["valor_total"].quantile(0.75)

    condiciones = [
        clientes["churn"] == 1,
        (clientes["frecuencia_compras"] >= q75_freq) & (clientes["valor_total"] >= q75_valor),
        clientes["frecuencia_compras"] >= q75_freq,
        clientes["frecuencia_compras"] <= q25_freq,
    ]

    segmentos = [
        "Inactivo",
        "Alto Valor",
        "Frecuente",
        "Ocasional",
    ]

    clientes["segmento"] = np.select(
        condiciones,
        segmentos,
        default="Regular"
    )

    clientes["fecha_registro"] = clientes["fecha_registro"].dt.date
    clientes["fecha_ultima_compra"] = clientes["fecha_ultima_compra"].dt.date

    columnas_finales = [
        "id_cliente",
        "nombre",
        "edad",
        "genero",
        "ciudad",
        "distrito",
        "fecha_registro",
        "canal_preferido",
        "segmento",
        "fecha_ultima_compra",
        "frecuencia_compras",
        "dias_desde_ultima_compra",
        "churn",
    ]

    return clientes[columnas_finales]


# ============================================================
# GENERACIÓN DE INVENTARIO
# ============================================================

def generar_inventario(
    ventas_df: pd.DataFrame,
    productos_df: pd.DataFrame,
    tiendas_df: pd.DataFrame
) -> pd.DataFrame:

    ventas_tmp = ventas_df.copy()
    ventas_tmp["periodo"] = ventas_tmp["fecha"].dt.to_period("M").astype(str)

    ventas_mensuales = ventas_tmp.groupby(
        ["id_producto", "id_tienda", "periodo"],
        as_index=False
    ).agg(
        unidades_vendidas=("cantidad", "sum")
    )

    periodos = pd.period_range("2023-01", "2025-12", freq="M").astype(str)

    combinaciones = pd.MultiIndex.from_product(
        [
            productos_df["id_producto"].to_numpy(),
            tiendas_df["id_tienda"].to_numpy(),
            periodos,
        ],
        names=["id_producto", "id_tienda", "periodo"]
    ).to_frame(index=False)

    inventario_base = combinaciones.merge(
        ventas_mensuales,
        on=["id_producto", "id_tienda", "periodo"],
        how="left"
    )

    inventario_base["unidades_vendidas"] = inventario_base["unidades_vendidas"].fillna(0).astype(int)

    productos_lookup = productos_df.set_index("id_producto")
    tiendas_lookup = tiendas_df.set_index("id_tienda")

    costo_base_categoria = {
        "Abarrotes": 0.05,
        "Bebidas": 0.05,
        "Limpieza": 0.08,
        "Cuidado Personal": 0.10,
        "Electrohogar": 1.55,
        "Hogar": 0.35,
    }

    registros = []

    for (id_producto, id_tienda), grupo in inventario_base.groupby(["id_producto", "id_tienda"], sort=False):
        grupo = grupo.sort_values("periodo")

        categoria = productos_lookup.loc[id_producto, "categoria"]
        ciudad_tienda = tiendas_lookup.loc[id_tienda, "ciudad"]

        stock_actual = random.randint(40, 180)

        if categoria == "Electrohogar":
            stock_actual = random.randint(8, 35)
        elif categoria == "Hogar":
            stock_actual = random.randint(20, 80)

        for _, fila in grupo.iterrows():
            periodo = fila["periodo"]
            unidades_vendidas = int(fila["unidades_vendidas"])

            stock_inicial = int(stock_actual)

            seguridad = random.randint(15, 60)

            if categoria == "Electrohogar":
                seguridad = random.randint(3, 15)

            punto_objetivo = max(
                int(unidades_vendidas * np.random.uniform(1.15, 1.65)),
                seguridad
            )

            reabastecimiento = max(punto_objetivo - stock_inicial + unidades_vendidas, 0)
            stock_final = max(stock_inicial + reabastecimiento - unidades_vendidas, 0)

            costo_unitario = costo_base_categoria[categoria] * np.random.uniform(0.85, 1.25)

            if ciudad_tienda == "Trujillo" and periodo >= "2025-04":
                costo_unitario *= np.random.uniform(1.65, 2.10)

            costo_unitario = round(float(costo_unitario), 2)
            costo_total = round(stock_final * costo_unitario, 2)

            registros.append(
                {
                    "id_producto": int(id_producto),
                    "id_tienda": int(id_tienda),
                    "periodo": periodo,
                    "stock_inicial": stock_inicial,
                    "unidades_vendidas": unidades_vendidas,
                    "reabastecimiento": int(reabastecimiento),
                    "stock_final": int(stock_final),
                    "costo_almacenamiento_unitario": costo_unitario,
                    "costo_almacenamiento_total": costo_total,
                }
            )

            stock_actual = stock_final

    return pd.DataFrame(registros)


# ============================================================
# CALIDAD DE DATOS: FALTANTES CONTROLADOS
# ============================================================

def aplicar_calidad_datos(
    clientes_df: pd.DataFrame,
    ventas_df: pd.DataFrame
) -> tuple[pd.DataFrame, pd.DataFrame]:

    clientes = clientes_df.copy()
    ventas = ventas_df.copy()

    clientes = insertar_faltantes(clientes, "canal_preferido", 0.015)
    clientes = insertar_faltantes(clientes, "distrito", 0.012)

    ventas = insertar_faltantes(ventas, "metodo_pago", 0.020)
    ventas = insertar_faltantes(ventas, "descuento_pct", 0.010)

    return clientes, ventas


# ============================================================
# VALIDACIONES
# ============================================================

def validar_volumenes(
    tiendas_df: pd.DataFrame,
    productos_df: pd.DataFrame,
    clientes_df: pd.DataFrame,
    ventas_df: pd.DataFrame,
    inventario_df: pd.DataFrame
) -> None:

    assert len(tiendas_df) == 12, "Error: tiendas.csv debe tener 12 registros."
    assert len(productos_df) == 800, "Error: productos.csv debe tener 800 registros."
    assert len(clientes_df) == 15_000, "Error: clientes.csv debe tener 15 000 registros."
    assert 150_000 <= len(ventas_df) <= 300_000, "Error: ventas.csv debe estar entre 150 000 y 300 000 líneas."

    inventario_esperado = 800 * 12 * 36
    assert len(inventario_df) == inventario_esperado, "Error: inventario.csv no tiene el número esperado de snapshots."


def validar_claves_foraneas(
    tiendas_df: pd.DataFrame,
    productos_df: pd.DataFrame,
    clientes_df: pd.DataFrame,
    ventas_df: pd.DataFrame,
    inventario_df: pd.DataFrame
) -> None:

    assert set(ventas_df["id_cliente"]).issubset(set(clientes_df["id_cliente"])), \
        "Error: ventas.csv contiene id_cliente inválidos."

    assert set(ventas_df["id_tienda"]).issubset(set(tiendas_df["id_tienda"])), \
        "Error: ventas.csv contiene id_tienda inválidos."

    assert set(ventas_df["id_producto"]).issubset(set(productos_df["id_producto"])), \
        "Error: ventas.csv contiene id_producto inválidos."

    assert set(inventario_df["id_producto"]).issubset(set(productos_df["id_producto"])), \
        "Error: inventario.csv contiene id_producto inválidos."

    assert set(inventario_df["id_tienda"]).issubset(set(tiendas_df["id_tienda"])), \
        "Error: inventario.csv contiene id_tienda inválidos."


def validar_calculos_ventas(ventas_df: pd.DataFrame) -> None:
    mascara = ventas_df["descuento_pct"].notna()

    calc_monto = np.round(
        ventas_df.loc[mascara, "cantidad"]
        * ventas_df.loc[mascara, "precio_unitario"]
        * (1 - ventas_df.loc[mascara, "descuento_pct"]),
        2
    )

    calc_margen_unitario = np.round(
        ventas_df.loc[mascara, "precio_unitario"]
        * (1 - ventas_df.loc[mascara, "descuento_pct"])
        - ventas_df.loc[mascara, "costo_unitario"],
        2
    )

    calc_margen_total = np.round(
        ventas_df.loc[mascara, "monto_total"]
        - (ventas_df.loc[mascara, "cantidad"] * ventas_df.loc[mascara, "costo_unitario"]),
        2
    )

    assert np.allclose(calc_monto, ventas_df.loc[mascara, "monto_total"], atol=0.03), \
        "Error: monto_total no es coherente."

    assert np.allclose(calc_margen_unitario, ventas_df.loc[mascara, "margen_unitario"], atol=0.03), \
        "Error: margen_unitario no es coherente."

    assert np.allclose(calc_margen_total, ventas_df.loc[mascara, "margen_total"], atol=0.03), \
        "Error: margen_total no es coherente."


def validar_calculos_inventario(inventario_df: pd.DataFrame) -> None:
    calc_stock_final = (
        inventario_df["stock_inicial"]
        + inventario_df["reabastecimiento"]
        - inventario_df["unidades_vendidas"]
    )

    calc_stock_final = calc_stock_final.clip(lower=0)

    calc_costo_total = np.round(
        inventario_df["stock_final"]
        * inventario_df["costo_almacenamiento_unitario"],
        2
    )

    assert np.array_equal(calc_stock_final.to_numpy(), inventario_df["stock_final"].to_numpy()), \
        "Error: stock_final no es coherente."

    assert np.allclose(calc_costo_total, inventario_df["costo_almacenamiento_total"], atol=0.03), \
        "Error: costo_almacenamiento_total no es coherente."


def validar_patrones(
    tiendas_df: pd.DataFrame,
    clientes_df: pd.DataFrame,
    ventas_df: pd.DataFrame,
    inventario_df: pd.DataFrame
) -> None:

    ventas = ventas_df.copy()
    ventas["fecha"] = pd.to_datetime(ventas["fecha"])
    ventas["mes"] = ventas["fecha"].dt.month
    ventas["anio"] = ventas["fecha"].dt.year

    ventas_por_mes = ventas.groupby("mes")["id_venta"].count()
    promedio_mensual = ventas_por_mes.mean()

    assert ventas_por_mes.loc[7] > promedio_mensual * 1.05, \
        "Error: no se observa pico de ventas en julio."

    assert ventas_por_mes.loc[12] > promedio_mensual * 1.10, \
        "Error: no se observa pico de ventas en diciembre."

    ventas["es_digital"] = ventas["canal"].isin(["Web", "App"]).astype(int)

    digital_2023 = ventas.loc[ventas["anio"] == 2023, "es_digital"].mean()
    digital_2025 = ventas.loc[ventas["anio"] == 2025, "es_digital"].mean()

    assert digital_2025 > digital_2023, \
        "Error: el canal digital no crece entre 2023 y 2025."

    ventas_tienda = ventas.merge(
        tiendas_df[["id_tienda", "ciudad"]],
        on="id_tienda",
        how="left"
    )

    trujillo = ventas_tienda[ventas_tienda["ciudad"] == "Trujillo"].copy()

    pre_q2 = trujillo[
        (trujillo["fecha"] >= pd.Timestamp("2024-04-01")) &
        (trujillo["fecha"] < pd.Timestamp("2025-04-01"))
    ]

    post_q2 = trujillo[
        trujillo["fecha"] >= pd.Timestamp("2025-04-01")
    ]

    margen_pre = margen_porcentual(pre_q2)
    margen_post = margen_porcentual(post_q2)

    assert margen_post < margen_pre, \
        "Error: no se observa caída de margen en Trujillo desde 2025-Q2."

    inventario_tienda = inventario_df.merge(
        tiendas_df[["id_tienda", "ciudad"]],
        on="id_tienda",
        how="left"
    )

    costo_trujillo_pre = inventario_tienda[
        (inventario_tienda["ciudad"] == "Trujillo") &
        (inventario_tienda["periodo"] < "2025-04")
    ]["costo_almacenamiento_unitario"].mean()

    costo_trujillo_post = inventario_tienda[
        (inventario_tienda["ciudad"] == "Trujillo") &
        (inventario_tienda["periodo"] >= "2025-04")
    ]["costo_almacenamiento_unitario"].mean()

    assert costo_trujillo_post > costo_trujillo_pre, \
        "Error: no se observa aumento del costo de almacenamiento en Trujillo."

    q25 = clientes_df["frecuencia_compras"].quantile(0.25)
    q75 = clientes_df["frecuencia_compras"].quantile(0.75)

    churn_baja_frecuencia = clientes_df[
        clientes_df["frecuencia_compras"] <= q25
    ]["churn"].mean()

    churn_alta_frecuencia = clientes_df[
        clientes_df["frecuencia_compras"] >= q75
    ]["churn"].mean()

    assert churn_baja_frecuencia >= churn_alta_frecuencia, \
        "Error: el churn no es mayor en clientes de baja frecuencia."


def validar_faltantes(clientes_df: pd.DataFrame, ventas_df: pd.DataFrame) -> None:
    campos = [
        ("clientes.canal_preferido", clientes_df["canal_preferido"].isna().mean()),
        ("clientes.distrito", clientes_df["distrito"].isna().mean()),
        ("ventas.metodo_pago", ventas_df["metodo_pago"].isna().mean()),
        ("ventas.descuento_pct", ventas_df["descuento_pct"].isna().mean()),
    ]

    for campo, pct in campos:
        assert 0.01 <= pct <= 0.03, \
            f"Error: el campo {campo} tiene {pct:.2%} de faltantes y debe estar entre 1% y 3%."


def ejecutar_validaciones(
    tiendas_df: pd.DataFrame,
    productos_df: pd.DataFrame,
    clientes_df: pd.DataFrame,
    ventas_df: pd.DataFrame,
    inventario_df: pd.DataFrame
) -> None:

    validar_volumenes(tiendas_df, productos_df, clientes_df, ventas_df, inventario_df)
    validar_claves_foraneas(tiendas_df, productos_df, clientes_df, ventas_df, inventario_df)
    validar_calculos_ventas(ventas_df)
    validar_calculos_inventario(inventario_df)
    validar_patrones(tiendas_df, clientes_df, ventas_df, inventario_df)
    validar_faltantes(clientes_df, ventas_df)


# ============================================================
# DICCIONARIO DE DATOS
# ============================================================

def generar_diccionario_datos() -> str:
    return """
# Diccionario de datos - AndinaRetail S.A.C.

## Descripción general

Los datos corresponden a una empresa ficticia peruana de retail omnicanal llamada AndinaRetail S.A.C.
Todos los registros son sintéticos y fueron generados mediante un script reproducible en Python usando semillas fijas.

El conjunto de datos permite desarrollar análisis estadístico, descriptivo, diagnóstico, predictivo, prescriptivo y tableros de control.

---

## Tabla: tiendas.csv

Descripción: contiene información maestra de las tiendas físicas y del canal virtual de AndinaRetail.

| Campo | Tipo de dato | Descripción | Dominio / valores permitidos | Observaciones |
|---|---|---|---|---|
| id_tienda | entero | Identificador único de tienda | 1 a 12 | Clave primaria |
| nombre | texto | Nombre ficticio de la tienda | Texto | No corresponde a una empresa real |
| ciudad | texto | Ciudad donde opera la tienda | Lima, Arequipa, Trujillo, Cusco, Piura | Incluye cobertura nacional para el canal virtual |
| region | texto | Región comercial asociada | Costa Centro, Norte, Sur, Sur Andino, Nacional | Variable descriptiva |
| tipo | texto | Tipo de tienda | Física, Virtual | El canal Web/App se asocia a tienda virtual |
| area_m2 | entero | Área aproximada de la tienda | 0 o valores positivos | La tienda virtual tiene área 0 |
| fecha_apertura | fecha | Fecha de apertura de la tienda | YYYY-MM-DD | Valor sintético |

---

## Tabla: productos.csv

Descripción: contiene el catálogo sintético de productos.

| Campo | Tipo de dato | Descripción | Dominio / valores permitidos | Observaciones |
|---|---|---|---|---|
| id_producto | entero | Identificador único del producto | 1 a 800 | Clave primaria |
| nombre | texto | Nombre ficticio del producto | Texto | Compuesto por subcategoría, marca ficticia y código |
| categoria | texto | Categoría comercial | Abarrotes, Bebidas, Limpieza, Cuidado Personal, Electrohogar, Hogar | Usada para análisis de ventas y demanda |
| subcategoria | texto | Subgrupo de producto | Depende de la categoría | Variable de detalle |
| marca | texto | Marca ficticia | Lista de marcas sintéticas | No representa marcas reales |
| precio_lista | decimal | Precio base del producto | Valores positivos | Varía por categoría |
| costo_unitario | decimal | Costo unitario del producto | 60% a 80% del precio_lista | Usado para calcular margen |
| fecha_alta | fecha | Fecha de alta del producto | 2021 a 2025 | Valor sintético |

---

## Tabla: clientes.csv

Descripción: contiene información sintética de clientes y variables derivadas para análisis de churn.

| Campo | Tipo de dato | Descripción | Dominio / valores permitidos | Observaciones |
|---|---|---|---|---|
| id_cliente | entero | Identificador único del cliente | 1 a 15000 | Clave primaria |
| nombre | texto | Nombre ficticio del cliente | Texto generado con Faker | No corresponde a personas reales |
| edad | entero | Edad del cliente | 18 a 80 | Distribución normal truncada |
| genero | texto | Género sintético | Femenino, Masculino, Otro | Variable demográfica |
| ciudad | texto | Ciudad de residencia | Lima, Arequipa, Trujillo, Cusco, Piura | Usada para análisis territorial |
| distrito | texto | Distrito de residencia | Distritos sintéticos por ciudad | Incluye faltantes controlados |
| fecha_registro | fecha | Fecha de registro del cliente | 2022 a 2025 | Coherente con la primera compra |
| canal_preferido | texto | Canal preferido del cliente | Tienda, Web, App | Incluye faltantes controlados |
| segmento | texto | Segmento comercial derivado | Inactivo, Alto Valor, Frecuente, Ocasional, Regular | Derivado de frecuencia, valor y churn |
| fecha_ultima_compra | fecha | Última fecha de compra del cliente | Fecha o vacío | Derivada de ventas.csv |
| frecuencia_compras | entero | Número de líneas de venta asociadas al cliente | 0 o mayor | Usada en churn |
| dias_desde_ultima_compra | entero | Días desde la última compra al 2025-12-31 | 0 o mayor | Si no compró, toma valor 999 |
| churn | entero | Indicador de inactividad | 1 = inactivo, 0 = activo | Churn = 1 si no compró en los últimos 90 días |

---

## Tabla: ventas.csv

Descripción: contiene líneas sintéticas de venta entre 2023 y 2025.

| Campo | Tipo de dato | Descripción | Dominio / valores permitidos | Observaciones |
|---|---|---|---|---|
| id_venta | entero | Identificador único de línea de venta | 1 a 250000 | Clave primaria |
| fecha | fecha | Fecha de venta | 2023-01-01 a 2025-12-31 | Incluye estacionalidad |
| id_cliente | entero | Cliente que realiza la compra | Debe existir en clientes.csv | Clave foránea |
| id_tienda | entero | Tienda asociada a la venta | Debe existir en tiendas.csv | Clave foránea |
| id_producto | entero | Producto vendido | Debe existir en productos.csv | Clave foránea |
| cantidad | entero | Unidades vendidas | Principalmente 1 a 8 | Incluye outliers controlados |
| precio_unitario | decimal | Precio unitario aplicado | Positivo | Derivado del precio_lista |
| descuento_pct | decimal | Descuento aplicado | 0.00 a 0.35 o faltante | 0.10 representa 10% |
| costo_unitario | decimal | Costo unitario del producto vendido | Positivo | Proviene de productos.csv |
| monto_total | decimal | Importe total de venta | Positivo | cantidad * precio_unitario * (1 - descuento_pct) |
| margen_unitario | decimal | Margen unitario | Puede ser bajo o negativo | precio neto - costo unitario |
| margen_total | decimal | Margen total de la línea | Puede ser bajo o negativo | monto_total - cantidad * costo_unitario |
| canal | texto | Canal de venta | Tienda, Web, App | Web/App crecen entre 2023 y 2025 |
| metodo_pago | texto | Método de pago | Efectivo, tarjetas, Yape, Plin, Transferencia | Incluye faltantes controlados |

---

## Tabla: inventario.csv

Descripción: contiene snapshots mensuales de inventario por producto y tienda.

| Campo | Tipo de dato | Descripción | Dominio / valores permitidos | Observaciones |
|---|---|---|---|---|
| id_producto | entero | Producto inventariado | Debe existir en productos.csv | Clave foránea |
| id_tienda | entero | Tienda inventariada | Debe existir en tiendas.csv | Clave foránea |
| periodo | texto | Periodo mensual | Formato AAAA-MM | Desde 2023-01 hasta 2025-12 |
| stock_inicial | entero | Stock inicial del periodo | 0 o mayor | Snapshot mensual |
| unidades_vendidas | entero | Unidades vendidas en el periodo | 0 o mayor | Derivado de ventas.csv |
| reabastecimiento | entero | Unidades repuestas | 0 o mayor | Generado para cubrir demanda |
| stock_final | entero | Stock final del periodo | 0 o mayor | stock_inicial + reabastecimiento - unidades_vendidas |
| costo_almacenamiento_unitario | decimal | Costo unitario de almacenamiento | Positivo | Aumenta en Trujillo desde 2025-Q2 |
| costo_almacenamiento_total | decimal | Costo total de almacenamiento | Positivo | stock_final * costo_almacenamiento_unitario |

---

## Patrones sintéticos incorporados

1. Estacionalidad:
   - Picos de ventas en julio por Fiestas Patrias.
   - Picos de ventas en diciembre por Navidad.
   - Mayor crecimiento del canal digital entre 2023 y 2025.

2. Patrón diagnóstico:
   - Desde el segundo trimestre de 2025, Trujillo presenta caída de margen.
   - La caída se explica por descuentos más altos y mayor costo de almacenamiento.

3. Churn:
   - Un cliente es inactivo si no compró en los últimos 90 días respecto al 2025-12-31.
   - La inactividad aumenta en clientes con baja frecuencia histórica.

4. Demanda predecible:
   - La cantidad vendida depende de categoría, mes, canal y descuento.
   - Se añade ruido aleatorio moderado.

5. Calidad de datos:
   - Se incorporan faltantes controlados entre 1% y 3%.
   - Se incorporan outliers controlados en cantidad y monto total.
"""


# ============================================================
# EXPORTACIÓN
# ============================================================

def exportar_archivos(
    tiendas_df: pd.DataFrame,
    productos_df: pd.DataFrame,
    clientes_df: pd.DataFrame,
    ventas_df: pd.DataFrame,
    inventario_df: pd.DataFrame
) -> None:

    tiendas_df.to_csv(OUTPUT_DIR / "tiendas.csv", index=False, encoding="utf-8")
    productos_df.to_csv(OUTPUT_DIR / "productos.csv", index=False, encoding="utf-8")
    clientes_df.to_csv(OUTPUT_DIR / "clientes.csv", index=False, encoding="utf-8")
    ventas_df.to_csv(OUTPUT_DIR / "ventas.csv", index=False, encoding="utf-8")
    inventario_df.to_csv(OUTPUT_DIR / "inventario.csv", index=False, encoding="utf-8")

    with open(OUTPUT_DIR / "data_dictionary.md", "w", encoding="utf-8") as archivo:
        archivo.write(generar_diccionario_datos())


# ============================================================
# RESUMEN FINAL
# ============================================================

def imprimir_resumen(
    tiendas_df: pd.DataFrame,
    productos_df: pd.DataFrame,
    clientes_df: pd.DataFrame,
    ventas_df: pd.DataFrame,
    inventario_df: pd.DataFrame
) -> None:

    ventas_tmp = ventas_df.copy()
    ventas_tmp["fecha"] = pd.to_datetime(ventas_tmp["fecha"])
    ventas_tmp["anio"] = ventas_tmp["fecha"].dt.year
    ventas_tmp["mes"] = ventas_tmp["fecha"].dt.month

    ventas_mes = ventas_tmp.groupby("mes")["id_venta"].count()
    digital = ventas_tmp.assign(
        es_digital=ventas_tmp["canal"].isin(["Web", "App"]).astype(int)
    ).groupby("anio")["es_digital"].mean()

    print("\n==============================================")
    print("GENERACIÓN FINALIZADA CORRECTAMENTE")
    print("==============================================")
    print(f"tiendas.csv:     {len(tiendas_df):,} registros")
    print(f"productos.csv:   {len(productos_df):,} registros")
    print(f"clientes.csv:    {len(clientes_df):,} registros")
    print(f"ventas.csv:      {len(ventas_df):,} registros")
    print(f"inventario.csv:  {len(inventario_df):,} registros")
    print("\nArchivos generados en la carpeta: datos/")

    print("\nValidaciones principales:")
    print("- Claves foráneas: OK")
    print("- Cálculos de monto, margen e inventario: OK")
    print("- Estacionalidad julio/diciembre: OK")
    print("- Crecimiento digital 2023-2025: OK")
    print("- Caída de margen en Trujillo desde 2025-Q2: OK")
    print("- Faltantes controlados 1%-3%: OK")

    print("\nVentas por mes:")
    print(ventas_mes.to_string())

    print("\nParticipación de canal digital por año:")
    print((digital * 100).round(2).astype(str).add("%").to_string())

    print("\nTasa de churn:")
    print(f"{clientes_df['churn'].mean() * 100:.2f}%")


# ============================================================
# FUNCIÓN PRINCIPAL
# ============================================================

def main() -> None:
    crear_directorio_salida()

    print("Generando tiendas...")
    tiendas_df = generar_tiendas()

    print("Generando productos...")
    productos_df = generar_productos()

    print("Generando clientes base...")
    clientes_base_df = generar_clientes_base()

    print("Generando ventas...")
    ventas_df = generar_ventas(
        tiendas_df=tiendas_df,
        productos_df=productos_df,
        clientes_df=clientes_base_df
    )

    print("Calculando variables de clientes y churn...")
    clientes_df = actualizar_clientes_con_churn(
        clientes_df=clientes_base_df,
        ventas_df=ventas_df
    )

    print("Generando inventario mensual...")
    inventario_df = generar_inventario(
        ventas_df=ventas_df,
        productos_df=productos_df,
        tiendas_df=tiendas_df
    )

    print("Aplicando faltantes controlados...")
    clientes_df, ventas_df = aplicar_calidad_datos(
        clientes_df=clientes_df,
        ventas_df=ventas_df
    )

    print("Ejecutando validaciones...")
    ejecutar_validaciones(
        tiendas_df=tiendas_df,
        productos_df=productos_df,
        clientes_df=clientes_df,
        ventas_df=ventas_df,
        inventario_df=inventario_df
    )

    print("Exportando archivos CSV y diccionario de datos...")
    exportar_archivos(
        tiendas_df=tiendas_df,
        productos_df=productos_df,
        clientes_df=clientes_df,
        ventas_df=ventas_df,
        inventario_df=inventario_df
    )

    imprimir_resumen(
        tiendas_df=tiendas_df,
        productos_df=productos_df,
        clientes_df=clientes_df,
        ventas_df=ventas_df,
        inventario_df=inventario_df
    )


if __name__ == "__main__":
    main()

